### ISSUE TITLE
StringIndexOutOfBoundsException with Maven Shell (1.2.0-SNAPSHOT,201704252044)

### ISSUE THREAD

**Issue by garydgregory** [jdillon/mvnsh#26] opened 2017-04-25 20:48 UTC
I just pulled the latest and built locally. When I run, I get:

```C:\vcs\git\github\jdillon\mvnsh>target\mvnsh-1.2.0-SNAPSHOT\bin\mvnsh
Maven Shell (1.2.0-SNAPSHOT,201704252044)

Type 'help' for more information.
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[INFO] Error reloading history file: C:\Users\ggregory\.m2\mvnsh.history
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1967)
        at org.jline.reader.impl.history.DefaultHistory.lambda$load$0(DefaultHistory.java:80)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at org.jline.reader.impl.history.DefaultHistory.load(DefaultHistory.java:78)
        at org.jline.reader.impl.history.DefaultHistory.attach(DefaultHistory.java:66)
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:464)
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:383)
        at com.planet57.gshell.console.Console.work(Console.java:105)
        at com.planet57.gshell.console.Console.run(Console.java:83)
        at com.planet57.gshell.shell.ShellImpl.run(ShellImpl.java:247)
        at com.planet57.gshell.MainSupport.boot(MainSupport.java:310)
        at com.planet57.maven.shell.Main.main(Main.java:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.planet57.gshell.launcher.Launcher.launch(Launcher.java:74)
        at com.planet57.gshell.launcher.Launcher.run(Launcher.java:46)
        at com.planet57.gshell.launcher.Launcher.main(Launcher.java:37)```

**Comment by mosabua** [comment] 2017-04-25 20:49
Duplicate of https://github.com/jdillon/mvnsh/issues/24

**Closed** 2017-04-25 20:56 UTC
